### ISSUE TITLE
Epic

### ISSUE THREAD

**Issue by theodorusclarence** [theodorusclarence/seasfor.us#1]
- [x] #2
- [x] #3
- [x] #9
- [x] #17
- [x] #8
- [x] #21
- [x] #18
- [x] #15

# Connect backend

- [x] #31
- [x] #25
- [x] #26
- [x] #37
- [x] #44
- [x] #38
- [x] #34
- [x] #32

**Comment by theodorusclarence** [comment]
# Connect backend

- [ ] Auth get user
- [ ] Events
- [ ] Event detail & Post
- [ ] Join button
- [ ] Post Activity (form)
- [ ] My events
- [ ] Leaderboard
